Add SegmentedControl support
guidomb/PortalView pull request #5
Opened 2017-04-05 20:36 UTC by cristianames92

This PR intents to add UISegmentedControl to the framework, wrapped in Segmented component

2017-04-05 21:17 UTC, guidomb requested changes

2017-04-05 21:17 UTC, guidomb commented on Sources/Components/Segmented.swift
> +    public var segments: [SegmentProperties<MessageType>]
Lets use the proposed alternative of using a zip list.

```swift
public var leftSegments: [SegmentProperties<MessageType>]
public var selectedSegment: SegmentProperties<MessageType>
public var rightSegments: [SegmentProperties<MessageType>]
```

2017-04-05 21:17 UTC, guidomb commented on Sources/UIKit/Renderers/ButtonRenderer.swift
> +        let dispatcher = MessageDispatcher(mailbox: mailbox) { _ in return message }
Here we could use the `init(mailbox:,message:)` initializer

2017-04-05 21:17 UTC, guidomb commented on Sources/UIKit/Renderers/SegmentedRendered.swift
> +//public let defaultButtonFontSize = UInt(UIFont.buttonFontSize)
Delete this

2017-04-05 21:17 UTC, guidomb commented on Sources/UIKit/Renderers/SegmentedRendered.swift
> +internal struct SegmentedControlDispatcher {
remove this

2017-04-05 21:17 UTC, guidomb commented on Sources/UIKit/Renderers/SegmentedRendered.swift
> +        self.addTarget(dispatcher, action: #selector(MessageDispatcher<MessageType>.dispatch), for: event)
just in case I would remove all previous registered targets.

2017-04-06 13:36 UTC, cristianames92 commented on Sources/UIKit/Renderers/SegmentedRendered.swift
> +        self.addTarget(dispatcher, action: #selector(MessageDispatcher<MessageType>.dispatch), for: event)
Targets are removed here https://github.com/cristianames92/PortalView/blob/master/Sources/UIKit/Renderers/SegmentedRenderer.swift#L40

2017-04-06 17:08 UTC, guidomb approved these changes

2017-04-06 17:09 UTC, merged