Add Text Field Implementation
guidomb/PortalView pull request #7
Opened 2017-04-10 16:17 UTC by jcaracciolo

Add TextField component with a given Implementation

2017-04-10 16:57 UTC, cristianames92 commented
Both `TextField` and `TextFieldRenderer` are in the main location and not under the correct one. Please reallocate those files.

2017-04-10 17:54 UTC, guidomb requested changes

2017-04-10 17:54 UTC, guidomb commented on Sources/Component.swift
> +            return .textField(properties.map(transform),style,layout)
Add spaces between `,` and parameter. This should be changed to

```swift
return .textField(properties.map(transform), style, layout)
```

2017-04-10 17:54 UTC, guidomb commented on Sources/Component.swift
> +public enum TextFieldMessage {
Delete this.

2017-04-10 17:54 UTC, guidomb commented on TextField.swift
> +    public var textAfterLayout: String?
This should not be necessary for this component.

2017-04-10 17:54 UTC, guidomb commented on TextField.swift
> +
Missing `placeholder: String?` property.

2017-04-10 17:54 UTC, guidomb commented on TextField.swift
> +public struct OnTextFieldEvents<MessageType> {
This type should be an inner type inside `TextFieldProperties`

```swift
public struct TextFieldProperties<MessageType> {

  public struct Message {

    public let onBeginEditing: MessageType?
    public let onInputChange: MessageType?
    public let onEndEditing: MessageType?

  }

}
```

2017-04-10 17:54 UTC, guidomb commented on TextFieldRenderer.swift
> +            if let textAfterLayout = self.properties.textAfterLayout, let size = textField.maximumFontSizeForWidth() {
This is not necessary

2017-04-12 11:43 UTC, jcaracciolo commented on TextField.swift
> +public struct OnTextFieldEvents<MessageType> {
A new type cannot be nested inside a generic type like TextFieldProperties. [Reference](https://forums.developer.apple.com/thread/12298)

2017-04-12 12:00 UTC, guidomb commented on TextField.swift
> +public struct OnTextFieldEvents<MessageType> {
Yes it can. I've done before. USE Xcode 8.3.1

2017-04-12 12:23 UTC, jcaracciolo commented on TextField.swift
> +public struct OnTextFieldEvents<MessageType> {
I will upgrade now and try it

2017-04-12 18:39 UTC, guidomb approved these changes

2017-04-12 18:39 UTC, merged